frame_color = "{{color4}}"
highlight = "{{color5}}"
separator_color= "{{foreground}}"

[urgency_low]
background = "{{background}}"
foreground = "{{foreground}}"
frame_color = "{{color6}}"

[urgency_normal]
background = "{{background}}"
foreground = "{{foreground}}"
frame_color = "{{color4}}"

[urgency_critical]
background = "{{background}}"
foreground = "{{foreground}}"
frame_color = "{{color9}}"
