{ ... }:
{
  programs.floorp.profiles.default.settings = {
    "extensions.autoDisableScopes" = 0;
    "general.autoScroll" = true;
    "media.videocontrols.picture-in-picture.video-toggle.enabled" = false;
    "browser.translations.automaticallyPopup" = false;
    "svg.context-properties.content.enabled" = true;
    "toolkit.legacyUserProfileCustomizations.stylesheets" = true;
    "extensions.update.autoUpdateDefault" = true;
    "extensions.update.enabled" = true;
    ## ------ Privacy ------
    "privacy.clearHistory.cookiesAndStorage" = false;
    "privacy.clearHistory.formdata" = true;
    "privacy.clearOnShutdown_v2.cache" = true;
    "privacy.clearOnShutdown_v2.cookiesAndStorage" = false;
    "privacy.clearOnShutdown_v2.formdata" = true;
    "browser.startup.couldRestoreSession.count" = true;

    ## ----- FPP -----
    "privacy.resistFingerprinting" = true;
    "privacy.resistFingerprinting.letterboxing" = true;
    "privacy.fingerprintingProtection.overrides" =
      "+AllTargets,-CanvasExtractionBeforeUserInputIsBlocked,-CSSPrefersColorScheme,-FrameRate";
    ## ----- WEBRTC -----
    "media.peerconnection.enabled" = true;
    "privacy.webrtc.allowSilencingNotifications" = true;
    "privacy.webrtc.hideGlobalIndicator" = true;
    "media.peerconnection.mtransport_process" = true;
    "privacy.webrtc.globalMuteToggles" = true;
    "media.peerconnection.ice.obfuscate_host_addresses" = true;
    "media.peerconnection.ice.proxy_only_if_behind_proxy" = true;
    "privacy.webrtc.sharedTabWarning" = true;
    "media.peerconnection.ice.no_host" = true;
    "media.peerconnection.ice.default_address_only" = true;
    "media.peerconnection.ice.relay_only" = true;
    "network.http.referer.XOriginPolicy" = "2";
    ## ------ Jit ------
    "javascript.options.asmjs" = false;
    "javascript.options.ion" = false;
    "javascript.options.baselinejit" = false;
    "javascript.options.jit_trustedprincipals" = true;
    "javascript.options.wasm" = false;
    ## ------ UI/Theme ------
    "widget.gtk.libadwaita-colors.enabled" = false;
    "widget.non-native-theme.gtk.scrollbar.round-thumb" = false;
    # "browser.uiCustomization.state" = "{"placements":{"widget-overflow-fixed-list":[],"unified-extensions-area":["ublock0_raymondhill_net-browser-action","sponsorblocker_ajay_app-browser-action","_3c078156-979c-498b-8990-85f7987dd929_-browser-action","addon_darkreader_org-browser-action"],"nav-bar":["back-button","forward-button","customizableui-special-spring1","vertical-spacer","urlbar-container","customizableui-special-spring2","stop-reload-button","undo-closed-tab","unified-extensions-button","downloads-button"],"toolbar-menubar":["menubar-items"],"TabsToolbar":["tabbrowser-tabs","alltabs-button"],"vertical-tabs":[],"PersonalToolbar":["import-button","personal-bookmarks"],"nora-statusbar":["screenshot-button","fullscreen-button","status-text"]},"seen":["developer-button","profile-manager-button","undo-closed-tab","workspaces-toolbar-button","addon_darkreader_org-browser-action","_3c078156-979c-498b-8990-85f7987dd929_-browser-action","sponsorblocker_ajay_app-browser-action","ublock0_raymondhill_net-browser-action","screenshot-button"],"dirtyAreaCache":["nav-bar","vertical-tabs","nora-statusbar","TabsToolbar","unified-extensions-area","PersonalToolbar","toolbar-menubar","widget-overflow-fixed-list"],"currentVersion":23,"newElementCount":11}";
    # XDG
    "widget.use-xdg-desktop-portal.file-picker" = "1";
    "widget.use-xdg-desktop-portal.location" = "1";
    "widget.use-xdg-desktop-portal.mime-handler" = "1";
    # "widget.use-xdg-desktop-portal.native-messaging" = "0";
    "widget.use-xdg-desktop-portal.open-uri" = "1";
    "widget.use-xdg-desktop-portal.settings" = "1";
    ## ------ Misc ------
    "permissions.default.shortcuts" = 1; # https://github.com/tridactyl/tridactyl/issues/4461#issuecomment-1315958996
    "extensions.webcompat-reporter.enabled" = false;
    "editor.truncate_user_pastes" = false;
    #
    ## ----- Data Collection -----
    #
    "network.dns.localDomains" =
      "250analytics.com,a.omappapi.com,activity-stream-icons.services.mozilla.com,ads.allizom.org,ads.mozilla.org,ads.nonprod.webservices.mozgcp.net,ads.prod.webservices.mozgcp.net,ads-img.mozilla.org,analytics.getpocket.com,analytics.google.com,analytics.withgoogle.com,anf1.fuzzing.mozilla.org,anonymco.com,api.divviup.org,asan-nightly-frontend-elb-1348905149.us-east-2.elb.amazonaws.com,braze.com,contile.services.mozilla.com,contile-images.services.mozilla.com,classify-client.nonprod.webservices.mozgcp.net,classify-client.prod.webservices.mozgcp.net,classify-client.services.mozilla.com,crash-reports.allizom.org,crash-reports.mozilla.com,crash-reports-xpsp2.mozilla.com,crash-stacks.mozilla.com,crash-stats.allizom.org,crash-stats.mozilla.com,crash-stats.mozilla.org,dap.services.mozilla.com,dap.nonprod.webservices.mozgcp.net,dap.prod.webservices.mozgcp.net,dap-09-3.api.divviup.org,data.mozilla.com,data-ingestion.prod.dataops.mozgcp.net,dataops.mozgcp.net,dataservices.mozgcp.net,debug-ping-preview.firebaseapp.com,discovery.addons.allizom.org,discovery.addons.mozilla.org,discovery.addons-dev.allizom.org,divviup.org,download-stats.mozilla.org,download-stats.r53-2.services.mozilla.com,experimenter.services.mozilla.com,experimenter.nonprod.webservices.mozgcp.net,experimenter.prod.webservices.mozgcp.net,fhr.data.mozilla.com,fhr.r53-2.services.mozilla.com,firefox-android-home-recommendations.getpocket.com,firefox-dns-perf-test.net,fuzzing.mozilla.org,google-analytics.com,google-analytics-cn.com,googleanalytics.com,googlesyndication.com,googlesyndication-cn.com,googletagmanager.com,googletagmanager-cn.com,googletagservices.com,googletagservices-cn.com,improving.duckduckgo.com,incoming.glean.example.com,incoming.telemetry.mozilla.org,incoming.thunderbird.net,incoming-telemetry.thunderbird.net,ingestion-edge.prod.dataops.mozgcp.net,location.services.mozilla.com,locprod1-elb-eu-west-1.prod.mozaws.net,locprod2-elb-us-west-2.prod.mozaws.net,metrics-content.duckduckgo.com,new-sentry.gitlab.net,nonprod.classify-client.nonprod.webservices.mozgcp.net,normandy.cdn.mozilla.net,normandy.nonprod.cloudops.mozgcp.net,normandy.prod.cloudops.mozgcp.net,normandy-cdn.services.mozilla.com,omappapi.com,pipeline-incoming-prod-elb-149169523.us-west-2.elb.amazonaws.com,prod.ads.prod.webservices.mozgcp.net,prod.classify-client.prod.webservices.mozgcp.net,prod.dap.prod.webservices.mozgcp.net,prod.data-ingestion.prod.dataops.mozgcp.net,prod.dataops.mozgcp.net,prod.experimenter.prod.webservices.mozgcp.net,prod.ingestion-edge.prod.dataops.mozgcp.net,prod.sentry.prod.cloudops.mozgcp.net,prod-classifyclient.normandy.prod.cloudops.mozgcp.net,profile.accounts.firefox.com,sdk.iad-05.braze.com,search.r53-2.services.mozilla.com,search.services.mozilla.com,self-repair.mozilla.org,self-repair.r53-2.services.mozilla.com,sentry.gitlab.net,sentry.io,sentry.nonprod.cloudops.mozgcp.net,sentry.prod.cloudops.mozgcp.net,sentry.prod.mozaws.net,sitereview.zscaler.com,snippets.allizom.org,snippets.cdn.mozilla.net,snippets.mozilla.com,snippets-prod.frankfurt.moz.works,snippets-prod.moz.works,snippets-prod.oregon-b.moz.works,snippets-stage.moz.works,snippets-stage.oregon-b.moz.works,snowplow.trx.gitlab.net,snowplowalb-1011729428.us-east-1.elb.amazonaws.com,snowplowprd.trx.gitlab.net,snowplowprdnlb-1490493263.us-east-2.elb.amazonaws.com,socorro.nonprod.webservices.mozgcp.net,socorro.prod.webservices.mozgcp.net,socorro-collector.services.mozilla.com,socorro-webapp-allizom.stage.mozaws.net,socorro-webapp.services.mozilla.com,spocs.getpocket.com,spocs.getpocket.dev,spocs.mozilla.net,ssl.google-analytics.com,ssl-google-analytics.l.google.com,stage.sentry.nonprod.cloudops.mozgcp.net,start.fedoraproject.org,start.thunderbird.net,start.ubuntu.com,start-stage.thunderbird.net,survey.mozilla.com,tagmanager.google.com,talkback.mozilla.org,talkback-public.mozilla.org,talkback-reports.mozilla.org,telemetry-coverage.mozilla.org,telemetry-coverage.r53-2.services.mozilla.com,telemetry-experiment.cdn.mozilla.net,telemetry-incoming.r53-2.services.mozilla.com,telemetry-incoming-a.r53-2.services.mozilla.com,telemetry-incoming-b.r53-2.services.mozilla.com,telemetry-prod-1054754349.us-east-1.elb.amazonaws.com,tiles-cdn.prod.ads.prod.webservices.mozgcp.net,updates.thunderbird.net,updates-stage.thunderbird.net,use-application-dns.net,vf.startpage.com,widgets.getpocket.com,www.250analytics.com,www.anonymco.com,www.google-analytics.com,www.google-analytics-cn.com,www.googleanalytics.com,www.googlesyndication.com,www.googlesyndication-cn.com,www.googletagmanager.com,www.googletagmanager-cn.com,www.googletagservices.com,www.googletagservices-cn.com,www.sentry.io,www-google-analytics.l.google.com,www-googletagmanager.l.google.com";
    "toolkit.aboutLogging.uploadProfileToCloud" = false;
    "toolkit.aboutlogging.uploadProfileUrl" = "";
    "browser.engagement.ctrlTab.has-used" = true;
    "browser.engagement.downloads-button.has-used" = true;
    "browser.engagement.fxa-toolbar-menu-button.has-used" = true;
    "browser.engagement.home-button.has-used" = true;
    "browser.engagement.library-button.has-used" = true;
    "browser.engagement.sidebar-button.has-used" = true;
    "browser.engagement.total_uri_count.pbm" = false;
    "browser.engagement.search_counts.pbm" = false;
    "browser.search.totalSearches" = "100";
    "toolkit.coverage.enabled" = false;
    "toolkit.coverage.endpoint.base" = "";
    "toolkit.coverage.log-level" = "70";
    "toolkit.coverage.opt-out" = true;
    "toolkit.telemetry.coverage.opt-out" = true;
    "asanreporter.apiurl" = "";
    "asanreporter.clientid" = "unknown";
    "asanreporter.loglevel" = "70";
    "breakpad.reportURL" = "";
    "browser.crashReports.crashPull" = false;
    "browser.crashReports.requestedNeverShowAgain" = true;
    "browser.crashReports.unsubmittedCheck.autoSubmit2" = false;
    "browser.crashReports.unsubmittedCheck.enabled" = false;
    "browser.tabs.crashReporting.includeURL" = false;
    "browser.tabs.crashReporting.sendReport" = false;
    "toolkit.crashreporter.include_context_heap" = false;
    "browser.aboutwelcome.entrypoint" = "";
    "browser.safebrowsing.features.emailtracking.datacollection.update" = false;
    "captchadetection.actor.enabled" = false;
    "captchadetection.hasUnsubmittedData" = false;
    "captchadetection.loglevel" = "Off";
    "datareporting.dau.cachedUsageProfileID" = "beefbeef-beef-beef-beef-beeefbeefbee";
    "datareporting.dau.cachedUsageProfileGroupID" = "b0bacafe-b0ba-cafe-b0ba-cafeb0bacafe";
    "datareporting.healthreport.uploadEnabled" = false;
    "datareporting.policy.dataSubmissionEnabled" = false;
    "datareporting.policy.dataSubmissionPolicyBypassNotification" = true;
    "datareporting.policy.firstRunURL" = "";
    "datareporting.usage.uploadEnabled" = false;
    "dom.security.unexpected_system_load_telemetry_enabled" = false;
    "extensions.dataCollectionPermissions.enabled" = false;
    "extensions.telemetry.EnvironmentAddonBuilder" = false;
    "network.jar.record_failure_reason" = false;
    "network.traffic_analyzer.enabled" = false;
    "network.trr.confirmation_telemetry_enabled" = false;
    "nimbus.telemetry.targetingContextEnabled" = false;
    "privacy.imageInputTelemetry.enableTestMode" = false;
    "privacy.trackingprotection.emailtracking.data_collection.enabled" = false;
    "telemetry.fog.aboutGlean.debugTag" = "";
    "telemetry.fog.artifact_build" = false;
    "telemetry.fog.test.activity_limit" = "-1";
    "telemetry.fog.test.inactivity_limit" = "-1";
    "telemetry.fog.init_on_shutdown" = false;
    "telemetry.fog.test.localhost_port" = "70000";
    "telemetry.glean.internal.finalInactive" = false;
    "telemetry.glean.internal.maxPingsPerMinute" = "0";
    "telemetry.number_of_site_origin.min_interval" = "999999999";
    "toolkit.content-background-hang-monitor.disabled" = true;
    "toolkit.telemetry.archive.enabled" = false;
    "toolkit.telemetry.bhrPing.enabled" = false;
    "toolkit.telemetry.cachedClientID" = "c0ffeec0-ffee-c0ff-eec0-ffeec0ffeec0";
    "toolkit.telemetry.cachedProfileGroupID" = "decafdec-afde-cafd-ecaf-decafdecafde";
    "toolkit.telemetry.collectInterval" = "999999999";
    "toolkit.telemetry.dap.helper.hpke" = "";
    "toolkit.telemetry.dap.helper.url" = "";
    "toolkit.telemetry.dap.leader.hpke" = "";
    "toolkit.telemetry.dap.leader.url" = "";
    "toolkit.telemetry.dap.logLevel" = "Off";
    "toolkit.telemetry.dap_enabled" = false;
    "toolkit.telemetry.dap_task1_enabled" = false;
    "toolkit.telemetry.dap_task1_taskid" = "";
    "toolkit.telemetry.dap_visit_counting_enabled" = false;
    "toolkit.telemetry.dap_visit_counting_experiment_list" = "[]";
    "toolkit.telemetry.debugSlowSql" = false;
    "toolkit.telemetry.enabled" = false;
    "toolkit.telemetry.eventping.maximumFrequency" = "999999999";
    "toolkit.telemetry.eventping.minimumFrequency" = "999999999";
    "toolkit.telemetry.firstShutdownPing.enabled" = false;
    "toolkit.telemetry.healthping.enabled" = false;
    "toolkit.telemetry.initDelay" = "999999999";
    "toolkit.telemetry.log.dump" = false;
    "toolkit.telemetry.log.level" = "Fatal";
    "toolkit.telemetry.minSubsessionLength" = "999999999";
    "toolkit.telemetry.newProfilePing.delay" = "999999999";
    "toolkit.telemetry.newProfilePing.enabled" = false;
    "toolkit.telemetry.overrideUpdateChannel" = "release";
    "toolkit.telemetry.previousBuildID" = "";
    "toolkit.telemetry.reportingpolicy.firstRun" = false;
    "toolkit.telemetry.scheduler.idleTickInterval" = "999999999";
    "toolkit.telemetry.scheduler.tickInterval" = "999999999";
    "toolkit.telemetry.send.overrideOfficialCheck" = false;
    "toolkit.telemetry.server" = "data;";
    "toolkit.telemetry.server_owner" = "";
    "toolkit.telemetry.shutdownPingSender.backgroundtask.enabled" = false;
    "toolkit.telemetry.shutdownPingSender.enabled" = false;
    "toolkit.telemetry.shutdownPingSender.enabledFirstSession" = false;
    "toolkit.telemetry.testing.disableFuzzingDelay" = false;
    "toolkit.telemetry.testing.overridePreRelease" = false;
    "toolkit.telemetry.testing.overrideProductsCheck" = false;
    "toolkit.telemetry.testing.suppressPingsender" = true;
    "toolkit.telemetry.translations.logLevel" = "Off";
    "toolkit.telemetry.unified" = false;
    "toolkit.telemetry.untrustedModulesPing.frequency" = "999999999";
    "toolkit.telemetry.updatePing.enabled" = false;
    "toolkit.telemetry.user_characteristics_ping.current_version" = "0";
    "toolkit.telemetry.user_characteristics_ping.last_version_sent" = "0";
    "toolkit.telemetry.user_characteristics_ping.logLevel" = "Off";
    "toolkit.telemetry.user_characteristics_ping.opt-out" = true;
    "toolkit.telemetry.user_characteristics_ping.send-once" = false;
    "toolkit.telemetry.user_characteristics_ping.uuid" = "";
    "urlclassifier.features.emailtracking.datacollection.allowlistTables" = "";
    "urlclassifier.features.emailtracking.datacollection.blocklistTables" = "";
    "app.normandy.run_interval_seconds" = "0";
    "app.normandy.api_url" = "";
    "app.normandy.enabled" = false;
    "app.normandy.experiments.lazy_classify" = true;
    "app.normandy.first_run" = false;
    "app.normandy.last_seen_buildid" = "";
    "app.normandy.logging.level" = "70";
    "app.normandy.user_id" = "";
    "app.shield.optoutstudies.enabled" = false;
    "messaging-system.log" = "off";
    "messaging-system.rsexperimentloader.collection_id" = "";
    "nimbus.appId" = "";
    "nimbus.profileId" = "";
    "nimbus.profilesdatastoreservice.enabled" = false;
    "nimbus.profilesdatastoreservice.read.enabled" = false;
    "nimbus.profilesdatastoreservice.sync.enabled" = false;
    "browser.preferences.experimental" = false;
    "about.glean.redesign.enabled" = false;
    "dom.origin-trials.enabled" = false;
    "app.distributor" = "";
    "app.distributor.channel" = "";
    "mozilla.partner.id" = "";
    #
    ## ----- AI -----
    #
    "extensions.htmlaboutaddons.local_model_management" = true;
    "browser.ml.chat.shortcuts.custom" = true;
    "browser.ml.chat.enabled" = false;
    "browser.ml.chat.menu" = false;
    "browser.ml.chat.page" = false;
    "extensions.formautofill.ml.experiment.enabled" = false;
    "browser.ml.linkPreview.enabled" = false;
    "browser.ml.linkPreview.longPress" = false;
    "browser.ml.linkPreview.optin" = false;
    "browser.ml.pageAssist.enabled" = false;
    "browser.urlbar.perplexity.hasBeenInSearchMode" = true;
    "browser.ml.smartAssist.apiKey" = "";
    "browser.ml.smartAssist.enabled" = false;
    "browser.ml.smartAssist.endpoint" = "";
    "browser.ml.smartAssist.model" = "";
    "browser.tabs.groups.smart.enabled" = false;
    "browser.tabs.groups.smart.optin" = false;
    "browser.tabs.groups.smart.userEnabled" = false;
    "browser.ml.linkPreview.blockListEnabled" = false;
    "browser.ml.chat.providers" = "";
    "browser.ml.chat.provider" = "https:\/\/duckduckgo.com\/?q=DuckDuckGo+AI+Chat&ia=chat";
    #
    ## ----- Geolocation -----
    #
    "permissions.default.geo" = "2";
    "geo.provider.network.logging.enabled" = false;
    "browser.region.local-geocoding" = false;
    "browser.region.network.scan" = false;
    "browser.region.network.url" = "";
    "browser.region.update.enabled" = false;
    "browser.search.region" = "US";
    "doh-rollout.home-region" = "US";
    "geo.provider.testing" = false;
    "geo.provider.use_mls" = false;
    "geo.provider.use_geoclue" = true;
    "geo.provider.network.debug.requestCache.enabled" = true;
    "geo.provider.geoclue.always_high_accuracy" = false;
    "geo.provider.network.url" = "https:#/api.beacondb.net/v1/geolocate";
    "browser.geolocation.warning.infoURL" = "https://phoenix.celenity.dev/geo";
    #
    ## ----- PDFJS -----
    #
    "pdfjs.enableAltTextModelDownload" = false;
    "pdfjs.enableAutoLinking" = false;
    "pdfjs.enableScripting" = false;
    "pdfjs.enableXfa" = false;
    "pdfjs.enableSignatureEditor" = true;
    "pdfjs.enableAltText" = true;
    "pdfjs.enableAltTextForEnglish" = true;
    "pdfjs.enableGuessAltText" = true;
    "pdfjs.enableNewAltTextWhenAddingImage" = true;
    "pdfjs.enableUpdatedAddImage" = true;
    "pdfjs.disableFontFace" = true;
    "pdfjs.textLayerMode" = "1";
    "browser.download.open_pdf_attachments_inline" = false;
    "pdfjs.disableRange" = true;
    "pdfjs.disableStream" = true;
    "pdfjs.enablePermissions" = false;
    "pdfjs.externalLinkTarget" = "2";
    "pdfjs.handleOctetStream" = false;
    "pdfjs.sidebarViewOnLoad" = "2";
    "pdfjs.historyUpdateUrl" = true;
    #
    ## ----- Misc Privacy Security -----
    #
    "accessibility.force_disabled" = "1";
    "devtools.accessibility.enabled" = false;
    "browser.search.update" = false;
    "dom.battery.enabled" = false;
    "beacon.enabled" = false;
    "dom.events.asyncClipboard.clipboardItem" = false;
    "dom.events.asyncClipboard.readText" = false;
    "dom.events.testing.asyncClipboard" = false;
    "browser.contentanalysis.default_result" = "0";
    "browser.contentanalysis.enabled" = false;
    "browser.contentanalysis.interception_point.clipboard.enabled" = false;
    "browser.contentanalysis.interception_point.drag_and_drop.enabled" = false;
    "browser.contentanalysis.interception_point.file_upload.enabled" = false;
    "browser.contentanalysis.interception_point.print.enabled" = false;
    "browser.contentanalysis.max_connections" = "0";
    "browser.contentanalysis.show_blocked_result" = true;
    "browser.contentanalysis.silent_notifications" = false;
    "dom.security.credentialmanagement.identity.enabled" = false;
    "dom.security.credentialmanagement.identity.heavyweight.enabled" = false;
    "dom.security.credentialmanagement.identity.lightweight.enabled" = false;
    "dom.reporting.crash.enabled" = false;
    "dom.reporting.enabled" = false;
    "dom.reporting.featurePolicy.enabled" = false;
    "dom.reporting.header.enabled" = false;
    "dom.reporting.testing.enabled" = false;
    "dom.webshare.enabled" = false;
    "dom.webshare.requireinteraction" = true;
    "dom.webgpu.enabled" = false;
    "dom.sitepermsaddon-provider.enabled" = false;
    "dom.webmidi.gated" = true;
    "network.lna.block_trackers" = true;
    "network.lna.enabled" = true;
    "network.lna.etp.enabled" = false;
    "network.lna.websocket.enabled" = true;
    "permissions.default.local-network" = "2";
    "permissions.default.localhost" = "2";
    "dom.origin-trials.mls.state" = "1";
    "dom.use_components_shim" = false;
    #
    ## ----- Misc Privacy -----
    #
    "network.security.ports.banned" =
      "29009, 29010, 30102, 30103, 12387, 12388, 12580, 12581, 12582, 12583, 12584, 12585, 12586, 12587, 12588, 12589, 12590, 12591";
    "security.csp.reporting.enabled" = false;
    "browser.send_pings" = false;
    "browser.send_pings.max_per_link" = "1";
    "browser.send_pings.require_same_host" = true;
    "network.http.network_error_logging.enabled" = false;
    "media.webspeech.service.endpoint" = "data;";
    "network.http.referer.hideOnionSource" = true;
    "dom.storage_access.auto_grants" = false;
    "privacy.restrict3rdpartystorage.heuristic.navigation" = false;
    "privacy.restrict3rdpartystorage.heuristic.opened_window_after_interaction" = false;
    "privacy.restrict3rdpartystorage.heuristic.recently_visited" = false;
    "privacy.restrict3rdpartystorage.heuristic.redirect" = false;
    "privacy.restrict3rdpartystorage.heuristic.window_open" = false;
    "security.ssl.disable_session_identifiers" = true;
    "privacy.userContext.enabled" = true;
    "cookiebanners.bannerClicking.enabled" = true;
    "cookiebanners.cookieInjector.enabled" = true;
    "cookiebanners.service.mode" = "1";
    "cookiebanners.service.mode.privateBrowsing" = "1";
    "cookiebanners.service.enableGlobalRules" = true;
    "cookiebanners.service.enableGlobalRules.subFrames" = true;
    "network.cookie.CHIPS.enabled" = true;
    "network.cookie.chips.partitionLimitDryRun" = false;
    "privacy.donottrackheader.enabled" = true;
    "privacy.globalprivacycontrol.enabled" = true;
    "privacy.globalprivacycontrol.functionality.enabled" = true;
    "privacy.globalprivacycontrol.pbmode.enabled" = true;
    "browser.profiles.enabled" = true;
    "privacy.userContext.ui.enabled" = true;
    "cookiebanners.ui.desktop.enabled" = true;
    "dom.storage_access.auto_grants.exclude_third_party_trackers" = true;
    "privacy.restrict3rdpartystorage.heuristic.exclude_third_party_trackers" = true;
    "privacy.query_stripping.strip_list" =
      "__hsfp __hssc __hstc __s _bhlid _branch_match_id _branch_referrer _gl _hsenc _kx _openstat at_recipient_id at_recipient_list bbeml bsft_clkid bsft_uid dclid et_rid fb_action_ids fb_comment_id fbclid gbraid gclid guce_referrer guce_referrer_sig hsCtaTracking igshid irclickid mc_eid mkt_tok ml_subscriber ml_subscriber_hash msclkid mtm_cid oft_c oft_ck oft_d oft_id oft_ids oft_k oft_lk oft_sk oly_anon_id oly_enc_id pk_cid rb_clickid s_cid sc_customer sc_eh sc_uid srsltid ss_email_id twclid unicorn_click_id vero_conv vero_id vgo_ee wbraid wickedid yclid ymclid ysclid";
    "privacy.query_stripping.allow_list" = "urldefense.com";
    "permissions.isolateBy.userContext" = true;
    "privacy.antitracking.isolateContentScriptResources" = true;
    "network.cookie.maxageCap" = "15552000";
    "browser.link.force_default_user_context_id_for_external_opens" = true;
    "autoadmin.append_emailaddr" = false;
    "privacy.dynamic_firstparty.limitForeign" = true;
    "network.http.referer.defaultPolicy.trackers" = "1";
    "network.http.referer.defaultPolicy.trackers.pbmode" = "1";
    "privacy.query_stripping.strip_on_share.enabled" = true;
    "network.http.referer.XOriginTrimmingPolicy" = "2";
    #
    ## ----- Misc Security -----
    #
    "security.default_personal_cert" = "Ask Every Time";
    "network.protocol-handler.warn-external.mailto" = true;
    "network.protocol-handler.warn-external-default" = true;
    "security.browser_xhtml_csp.enabled" = true;
    "security.browser_xhtml_csp.report-only" = false;
    "dom.ipc.keepProcessesAlive.extension" = "0";
    "dom.ipc.keepProcessesAlive.privilegedabout" = "0";
    "dom.ipc.keepProcessesAlive.web" = "0";
    "browser.gnome-search-provider.enabled" = false;
    "media.devices.insecure.enabled" = false;
    "media.getusermedia.insecure.enabled" = false;
    "network.security.ports.banned.override" = "";
    "security.sandbox.content.level" = "6";
    "browser.tabs.remote.coep.credentialless" = true;
    "browser.tabs.remote.useCrossOriginEmbedderPolicy" = true;
    "dom.origin-trials.coep-credentialless.state" = "1";
    "browser.tabs.remote.useCrossOriginOpenerPolicy" = true;
    "dom.security.setHTML.enabled" = true;
    "security.sandbox.gpu.level" = "2";
    "security.integrity_policy.enabled" = true;
    "security.integrity_policy.stylesheet.enabled" = true;
    "browser.opaqueResponseBlocking" = true;
    "browser.opaqueResponseBlocking.javascriptValidator" = true;
    "dom.origin_agent_cluster.default" = true;
    "dom.origin_agent_cluster.enabled" = true;
    "browser.sessionstore.disable_platform_collection" = false;
    "fission.autostart" = true;
    "fission.autostart.session" = true;
    "fission.disableSessionHistoryInParent" = false;
    "fission.webContentIsolationStrategy" = "1";
    "gfx.webrender.all" = true;
    "dom.security.sanitizer.enabled" = true;
    "security.sandbox.socket.process.level" = "1";
    "javascript.options.spectre.disable_for_isolated_content" = false;
    "javascript.options.wasm_memory_control" = true;
    "security.fileuri.strict_origin_policy" = true;
    "dom.block_external_protocol_in_iframes" = true;
    "dom.block_external_protocol_navigation_from_sandbox" = true;
    "security.all_resource_uri_content_accessible" = false;
    "security.allow_eval_in_parent_process" = false;
    "security.allow_eval_with_system_principal" = false;
    "security.allow_parent_unrestricted_js_loads" = false;
    "security.allow_unsafe_parent_loads" = false;
    "security.data_uri.block_toplevel_data_uri_navigations" = true;
    "media.libavcodec.allow-obsolete" = false;
    "network.protocol-handler.external.shell" = false;
    "dom.security.skip_about_page_has_csp_assert" = false;
    "browser.tabs.remote.subframesPreferUsed" = false;
    "javascript.options.content_process_write_protect_code" = true;
    "general.config.sandbox_enabled" = true;
    "browser.tabs.remote.enforceRemoteTypeRestrictions" = true;
    "network.cookie.sameSite.laxByDefault" = true;
    "network.cookie.sameSite.noneRequiresSecure" = true;
    "network.cookie.sameSite.schemeful" = true;
    "dom.workers.importScripts.enforceStrictMimeType" = true;
    "network.sniff.use_extension" = true;
    "security.block_fileuri_script_with_wrong_mime" = true;
    "security.block_Worker_with_wrong_mime" = true;
    "media.cubeb.sandbox" = true;
    "browser.tabs.remote.separateFileUriProcess" = true;
    "security.sandbox.warn_unprivileged_namespaces" = true;
    "security.turn_off_all_security_so_that_viruses_can_take_over_this_computer" = false;
    #
    ## ----- Performance -----
    #
    "browser.cache.jsbc_compression_level" = "3";
    "sidebar.animation.enabled" = false;
    "ui.panelAnimations" = "0";
    "ui.prefersReducedMotion" = "1";
    "ui.swipeAnimationEnabled" = "0";
    "layout.css.report_errors" = false;
    "extensions.logging.enabled" = false;
    "network.http.pacing.requests.enabled" = false;
    "browser.tabs.hoverPreview.enabled" = false;
    "browser.tabs.hoverPreview.showThumbnails" = false;
    "browser.preferences.defaultPerformanceSettings.enabled" = false;
    "javascript.options.wasm_simd_avx" = true;
    "javascript.options.wasm_branch_hinting" = true;
    "gfx.canvas.accelerated" = true;
    "gfx.canvas.accelerated.cache-items" = "32768";
    "gfx.canvas.accelerated.cache-size" = "4096";
    "layout.css.grid-template-masonry-value.enabled" = true;
    "network.fetchpriority.enabled" = true;
    "javascript.options.mem.gc_parallel_marking" = true;
    "javascript.options.wasm_relaxed_simd" = true;
    "media.ffmpeg.vaapi.enabled" = true;
    "gfx.webrender.compositor" = true;
    "media.cache_readahead_limit" = "600";
    "media.cache_readahead_limit.cellular" = "600";
    "media.cache_resume_threshold" = "300";
    "media.cache_resume_threshold.cellular" = "300";
    "media.throttle-cellular-regardless-of-download-rate" = false;
    "image.mem.decode_bytes_at_a_time" = "65536";
    "network.dnsCacheExpiration" = "3600";
    "network.dnsCacheExpirationGracePeriod" = "120";
    "network.dnsCacheEntries" = "10000";
    "media.cache_size.cellular" = "512000";
    "image.cache.size" = "10485760";
    "media.memory_cache_max_size" = "262144";
    "media.memory_caches_combined_limit_kb" = "1048576";
    "browser.cache.memory.capacity" = "131072";
    "browser.cache.memory.max_entry_size" = "20480";
    "gfx.content.skia-font-cache-size" = "32";
    "network.http.max-connections" = "1800";
    "network.http.max-persistent-connections-per-proxy" = "48";
    "network.http.max-persistent-connections-per-server" = "10";
    "network.http.max-urgent-start-excessive-connections-per-host" = "5";
    "network.http.request.max-start-delay" = "5";
    "network.ssl_tokens_cache_capacity" = "10240";
    "gfx.webrender.low-quality-pinch-zoom" = true;
    #
    ## ----- FIREFOX SUGGEST -----
    #
    "browser.urlbar.suggest.weather" = false;
    "browser.urlbar.weather.featureGate" = true;
    "browser.urlbar.amp.featureGate" = false;
    "browser.urlbar.suggest.amp" = false;
    "browser.urlbar.addons.featureGate" = true;
    "browser.urlbar.suggest.addons" = false;
    "browser.urlbar.exposureResults" = "";
    "browser.urlbar.keywordExposureResults" = "";
    "browser.urlbar.showExposureResults" = false;
    "browser.urlbar.fakespot.featureGate" = false;
    "browser.urlbar.suggest.fakespot" = false;
    "browser.urlbar.addons.minKeywordLength" = "4";
    "browser.urlbar.flightStatus.minKeywordLength" = "4";
    "browser.urlbar.market.minKeywordLength" = "4";
    "browser.urlbar.weather.minKeywordLength" = "4";
    "browser.urlbar.yelp.minKeywordLength" = "4";
    "browser.urlbar.yelpRealtime.minKeywordLength" = "4";
    "browser.urlbar.quicksuggest.enabled" = false;
    "browser.urlbar.flightStatus.featureGate" = true;
    "browser.urlbar.suggest.flightStatus" = false;
    "browser.urlbar.quicksuggest.mlEnabled" = false;
    "browser.urlbar.yelp.mlEnabled" = false;
    "browser.urlbar.mdn.featureGate" = true;
    "browser.urlbar.suggest.mdn" = false;
    "browser.urlbar.suggest.realtimeOptIn" = false;
    "browser.urlbar.quicksuggest.online.available" = false;
    "browser.urlbar.quicksuggest.online.enabled" = false;
    "browser.urlbar.quicksuggest.settingsUi" = "2";
    "browser.urlbar.suggest.quicksuggest.nonsponsored" = false;
    "browser.partnerlink.attributionURL" = "";
    "browser.partnerlink.campaign.topsites" = "";
    "browser.urlbar.market.featureGate" = true;
    "browser.urlbar.suggest.market" = false;
    "browser.urlbar.groupLabels.enabled" = false;
    "browser.urlbar.sponsoredTopSites" = false;
    "browser.urlbar.suggest.quicksuggest.sponsored" = false;
    "browser.urlbar.quicksuggest.contextualOptIn" = false;
    "browser.urlbar.quicksuggest.dataCollection.enabled" = false;
    "browser.urlbar.suggest.wikipedia" = false;
    "browser.urlbar.wikipedia.featureGate" = true;
    "browser.urlbar.suggest.yelp" = false;
    "browser.urlbar.suggest.yelpRealtime" = false;
    "browser.urlbar.yelp.featureGate" = false;
    "browser.urlbar.yelpRealtime.featureGate" = false;
    "browser.urlbar.importantDates.featureGate" = true;
    "browser.urlbar.suggest.importantDates" = true;
    "browser.urlbar.quicksuggest.rustEnabled" = true;
    "browser.urlbar.merino.endpointURL" = "https://merino.services.mozilla.com/api/v1/suggest";
    "browser.urlbar.merino.providers" = "accuweather,amo,flightaware,market,mdn,wikipedia"; # / [NO-ANDROID] [NO-MAIL]
    "browser.urlbar.yelp.serviceResultDistinction" = true; # / [NO-ANDROID] [NO-MAIL]
    #
    ## ----- SYNC -----
    #
    "services.sync.engine.addons" = false;
    "services.sync.engine.addresses" = false;
    "services.sync.engine.bookmarks" = false;
    "services.sync.engine.creditcards" = false;
    "services.sync.engine.history" = false;
    "services.sync.engine.passwords" = false;
    "services.sync.engine.prefs" = false;
    "services.sync.engine.tabs" = false;
    "identity.fxaccounts.toolbar.pxiToolbarEnabled" = false;
    "identity.fxaccounts.toolbar.pxiToolbarEnabled.monitorEnabled" = false;
    "identity.fxaccounts.toolbar.pxiToolbarEnabled.relayEnabled" = false;
    "identity.fxaccounts.toolbar.pxiToolbarEnabled.vpnEnabled" = false;
    "identity.mobilepromo.android" = "";
    "identity.mobilepromo.ios" = "";
    "identity.sendtabpromo.url" = "";
    "identity.fxaccounts.toolbar.syncSetup.panelAccessed" = true;
    "identity.fxaccounts.account.telemetry.sanitized_uid" = "";
    "identity.fxaccounts.telemetry.clientAssociationPing.enabled" = false;
    "services.sync.log.logger.telemetry" = "Fatal";
    "services.sync.telemetry.maxEventsCount" = "0";
    "services.sync.telemetry.maxPayloadCount" = "0";
    "services.sync.telemetry.submissionInterval" = "999999999";
    "services.sync.log.appender.file.level" = "Fatal";
    "services.sync.extension-storage.skipPercentageChance" = "0";
    "identity.fxaccounts.migrateToDevEdition" = false;
    "services.sync.sendVersionInfo" = false;
    "services.sync.prefs.sync.browser.bookmarks.autoExportHTML" = true;
    "services.sync.prefs.sync.browser.bookmarks.openInTabClosesMenu" = true;
    "services.sync.prefs.sync.browser.compactmode.show" = true;
    "services.sync.prefs.sync.browser.download.open_pdf_attachments_inline" = true;
    "services.sync.prefs.sync.browser.newtabpage.activity-stream.discoverystream.recentSaves.enabled" =
      true;
    "services.sync.prefs.sync.browser.newtabpage.activity-stream.improvesearch.handoffToAwesomebar" =
      true;
    "services.sync.prefs.sync.browser.newtabpage.activity-stream.showRecentSaves" = true;
    "services.sync.prefs.sync.browser.newtabpage.activity-stream.showWeather" = true;
    "services.sync.prefs.sync.browser.preferences.experimental" = true;
    "services.sync.prefs.sync.browser.privatebrowsing.resetPBM.enabled" = true;
    "services.sync.prefs.sync.browser.privateWindowSeparation.enabled" = true;
    "services.sync.prefs.sync.browser.search.openintab" = true;
    "services.sync.prefs.sync.browser.search.separatePrivateDefault.urlbarResult.enabled" = true;
    "services.sync.prefs.sync.browser.spin_cursor_while_busy" = true;
    "services.sync.prefs.sync.browser.tabs.groups.enabled" = true;
    "services.sync.prefs.sync.browser.tabs.loadBookmarksInTabs" = true;
    "services.sync.prefs.sync.browser.toolbars.bookmarks.visibility" = true;
    "services.sync.prefs.sync.browser.urlbar.openintab" = true;
    "services.sync.prefs.sync.browser.urlbar.suggest.calculator" = true;
    "services.sync.prefs.sync.browser.urlbar.suggest.clipboard" = true;
    "services.sync.prefs.sync.browser.urlbar.unitConversion.enabled" = true;
    "services.sync.prefs.sync.browser.urlbar.update2.engineAliasRefresh" = true;
    "services.sync.prefs.sync.browser.xul.error_pages.expert_bad_cert" = true;
    "services.sync.prefs.sync.browser.xul.error_pages.show_safe_browsing_details_on_load" = true;
    "services.sync.prefs.sync.devtools.chrome.enabled" = true;
    "services.sync.prefs.sync.devtools.command-button-measure.enabled" = true;
    "services.sync.prefs.sync.devtools.command-button-rulers.enabled" = true;
    "services.sync.prefs.sync.devtools.command-button-screenshot.enabled" = true;
    "services.sync.prefs.sync.devtools.dom.enabled" = true;
    "services.sync.prefs.sync.devtools.debugger.ui.editor-wrapping" = true;
    "services.sync.prefs.sync.dom.security.https_only_mode_error_page_user_suggestions" = true;
    "services.sync.prefs.sync.dom.security.https_only_mode_send_http_background_request" = true;
    "services.sync.prefs.sync.extensions.quarantineIgnoredByUser.{b86e4813-687a-43e6-ab65-0bde4ab75758}" =
      true;
    "services.sync.prefs.sync.extensions.quarantineIgnoredByUser.{d19a89b9-76c1-4a61-bcd4-49e8de916403}" =
      true;
    "services.sync.prefs.sync.findbar.highlightAll" = true;
    "services.sync.prefs.sync.layout.forms.reveal-password-button.enabled" = true;
    "services.sync.prefs.sync.media.autoplay.blocking_policy" = true;
    "services.sync.prefs.sync.media.ffmpeg.vaapi.enabled" = true;
    "services.sync.prefs.sync.middlemouse.paste" = true;
    "services.sync.prefs.sync.network.IDN_show_punycode" = true;
    "services.sync.prefs.sync.pdfjs.sidebarViewOnLoad" = true;
    "services.sync.prefs.sync.privacy.webrtc.globalMuteToggles" = true;
    "services.sync.prefs.sync.sidebar.main.tools" = true;
    "services.sync.prefs.sync.sidebar.revamp" = true;
    "services.sync.prefs.sync.startup.homepage_override_nimbus_disable_wnp" = true;
    "services.sync.prefs.sync.view_source.wrap_long_lines" = true;
    #
    ## ----- Extensions -----
    #
    "extensions.userContextIsolation.defaults.restricted" = "[]";
    "extensions.userContextIsolation.enabled" = true;

    "extensions.quarantineIgnoredByUser.{290ce447-2abb-4d96-8384-7256dd4a1c43}" = true; # Runet Censorship Bypass
    "extensions.quarantineIgnoredByUser.{446900e4-71c2-419f-a6a7-df9c091e268b}" = true; # Bitwarden
    "extensions.quarantineIgnoredByUser.{5d0d1f87-5991-42d3-98c3-54878ead1ed1}" = true; # Censor Tracker
    "extensions.quarantineIgnoredByUser.{6c00218c-707a-4977-84cf-36df1cef310f}" = true; # Port Authority
    "extensions.quarantineIgnoredByUser.{73a6fe31-595d-460b-a920-fcc0f8843232}" = true; # NoScript
    "extensions.quarantineIgnoredByUser.{b86e4813-687a-43e6-ab65-0bde4ab75758}" = true; # LocalCDN
    "extensions.quarantineIgnoredByUser.{d19a89b9-76c1-4a61-bcd4-49e8de916403}" = true; # Mullvad
    "extensions.quarantineIgnoredByUser.78272b6fa58f4a1abaac99321d503a20@proton.me" = true; # Proton Pass
    "extensions.quarantineIgnoredByUser.adguard-vpn@adguard.com" = true; # AdGuard VPN
    "extensions.quarantineIgnoredByUser.adguardadblocker@adguard.com" = true; # AdGuard
    "extensions.quarantineIgnoredByUser.crxviewer-firefox@robwu.nl" = true; # Extension source viewer - important since we add AMO (`addons.mozilla.org` to our restricted/quarantined domain list
    "extensions.quarantineIgnoredByUser.foxyproxy@eric.h.jung" = true; # FoxyProxy
    "extensions.quarantineIgnoredByUser.foxyproxy-basic@eric.h.jung" = true; # FoxyProxy Basic
    "extensions.quarantineIgnoredByUser.idcac-pub@guus.ninja" = true; # I still don't care about cookies
    "extensions.quarantineIgnoredByUser.jid1-BoFifL9Vbdl2zQ@jetpack" = true; # Decentraleyes
    "extensions.quarantineIgnoredByUser.jid1-KtlZuoiikVfFew@jetpack" = true; # GNU LibreJS
    "extensions.quarantineIgnoredByUser.jid1-MnnxcxisBPnSXQ@jetpack" = true; # Privacy Badger
    "extensions.quarantineIgnoredByUser.jid1-MnnxcxisBPnSXQ-eff@jetpack" = true; # Privacy Badger (from eff.org
    "extensions.quarantineIgnoredByUser.keepassxc-browser@keepassxc.org" = true; # KeePassXC-Browser
    "extensions.quarantineIgnoredByUser.skipredirect@sblask" = true; # Skip Redirect
    "extensions.quarantineIgnoredByUser.uBlock0@raymondhill.net" = true; # uBlock Origin
    "extensions.quarantineIgnoredByUser.uBOLiteRedux@raymondhill.net" = true; # uBlock Origin Lite
    "extensions.quarantineIgnoredByUser.vpn@proton.ch" = true; # Proton VPN
    "extensions.quarantineIgnoredByUser.@testpilot-containers" = true; # Firefox Multi-Account Containers

    "extensions.strictCompatibility" = false;
    "extensions.webextensions.remote" = true;
    "xpinstall.signatures.weakSignaturesTemporarilyAllowed" = false;
    "xpinstall.whitelist.add" = "";
    "extensions.addonAbuseReport.url" = "";
    "xpinstall.enabled" = false;
    "extensions.webapi.enabled" = false;
    "extensions.webapi.testing" = false;
    "extensions.webapi.testing.http" = false;
    "privacy.resistFingerprinting.block_mozAddonManager" = true;
    "extensions.install_origins.enabled" = true;
    "extensions.webextOptionalPermissionPrompts" = true;
    "extensions.blocklist.enabled" = true;
    "extensions.manifestV3.enabled" = true;
    "extensions.remoteSettings.disabled" = true;
    "extensions.quarantinedDomains.enabled" = true;
    "extensions.quarantinedDomains.uiDisabled" = false;

    "extensions.quarantinedDomains.list" =
      "autoatendimento.bb.com.br,ibpf.sicredi.com.br,ibpj.sicredi.com.br,internetbanking.caixa.gov.br,www.ib12.bradesco.com.br,www2.bancobrasil.com.br,10.0.0.1,192.168.1.1,192.168.50.1,1password.ca,1password.com,1password.eu,365online.com,account.amd.com,account.apple.com,account.asus.com,account.brave.com,account.collegeboard.org,account.live.com,account.microcenter.com,account.microsoft.com,account.nordpass.com,account.proton.me,account.sony.com,account.t-mobile.com,account-api.proton.me,accounts.1password.ca,accounts.1password.com,accounts.1password.eu,accounts.ent.1password.com,accounts.fedoraproject.org,accounts.firefox.com,accounts.google.com,accounts.nintendo.com,accounts.pixiv.net,accounts.scdn.co,accounts.snapchat.com,accounts.spotify.com,acs-home-prod-login-fde-hhd4d2h9drbfg7hy.a02.azurefd.net,addons.allizom.org,addons.mozilla.org,addons.thunderbird.net,admin.google.com,adyen.com,agrd.io,agreementexpress.net,alipay.com,alipayobjects.com,alipayplus.com,amazon.syf.com,amazonpay.in,amp.pandora.com,anz.com,anz.com.au,ap.www.namecheap.com,apay-us.amazon.com,api.pnc.com,api.stripe.com,api-auth.soundcloud.com,app.1password.ca,app.1password.com,app.1password.eu,app.advancedmd.com,app.dashlane.com,app.privacy.com,app.tuta.com,appleconnect.apple.com,appleid.apple.com,appleid.cdn-apple.com,applepay.cdn-apple.com,apply.commonapp.org,apps.apple.com,apps.microsoft.com,apps.obtainium.imranr.dev,api-dashboard.search.brave.com,apt.izzysoft.de,archive.mozilla.org,archlinux.org,argenta.be,artists.soundcloud.com,artists.spotify.com,asrock.com,asrockchina.com.cn,assets.loginwithamazon.com,att-yahoo.att.net,attestation.app,aur.archlinux.org,auth.adguard.io,auth.adguardaccount.com,auth.hulu.com,auth.meta.com,auth.max.com,auth.mozilla.auth0.com,auth.openai.com,auth.services.adobe.com,auth.sharefile.io,auth.synchronybank.com,auth.uber.com,auth.wikimedia.org,auth.zennioptical.com,b.stripecdn.com,bancogalicia.com.ar,bank99.at,bankaust.com.au,bankaustria.at,bankdirekt.at,bankeasy.com,bankofamerica.com,bankofireland.com,bankvic.com.au,belfius.be,belkart.by,belveb.by,bendigobank.com.au,binance.com,binance.us,bisq.network,bitpay.com,bitwarden.com,bkash.com,bnpparibasfortis.be,bobpony.com,braintree-api.com,braintreegateway.com,brave.com,brave-browser-apk-beta.s3.brave.com,brave-browser-apk-nightly.s3.brave.com,brave-browser-apk-release.s3.brave.com,build.opensuse.org,businessaccess.citibank.citigroup.com,businessonline-boi.com,cakepay.com,cakewallet.com,calendar.proton.me,calyxos.org,cardcomplete.com,cash.app,cbaccount.collegeboard.org,cbzsecure.com,cdn.akamai.steamstatic.com,cdn.mullvad.net,cdn.plaid.com,cdn.sso.mozilla.com,cdimage.debian.org,checkout.com,coinspot.com.au,commbank.com.au,console.accrescent.app,console.aws.amazon.com,console.cloud.google.com,consumer.intel.com,copr.fedorainfracloud.org,creditcall.com,crelan.be,cromite.org,dash.cloudflare.com,developer.apple.com,developer.nvidia.com,discord.gg,dist.torproject.org,dl.google.com,donate.torproject.org,download.cdn.mozilla.net,download.fedoraproject.org,download.gigabyte.com,download.lineageos.org,download.mozilla.org,download-installer.cdn.mozilla.net,download-installer-origin.cdn.mozilla.net,download-origin.cdn.mozilla.net,drive.google.com,drive.proton.me,dsadata.intel.com,easybanking.unifi-digitalbanking.com,easybankint.com,ebanking.easybank.at,eff.org,ente.io,epicmychart.nychhc.org,epicmychart.optum.com,etoro.com,f-droid.org,fdroid.ironfoxoss.org,fdroid.link,fedoraproject.org,flatex.at,flathub.org,flex.okta.com,franciscanmychart.org,franklincollege.okta.com,ftp.eu.mozilla.org,ftp.mozilla.org,ftp.prod.mozaws.net,ftp.prod.mozilla.org,ftp-ssl.mozilla.org,ftp-test.mozilla.org,galicia.ar,gateway.bank,gatewaybank.bank,gatewaybank.com.au,gatewayfirst.com,gds.google.com,geogroup.okta.com,george.sparkasse.at,george-business.sparkasse.at,gfgsa.com,google-admin.corp.google.com,grapheneos.org,greasyfork.org,guardarian.com,heartland.us,heartlandpaymentsystems.com,heartlandportico.com,hellobank.be,hendrick.okta.com,hpc.freedompay.com,hsbc.com,hsbc.com.au,icard.com,id.fedoraproject.org,id.sonyentertainmentnetwork.com,id.spectrum.net,identity.corp.google.com,identity.doordash.com,identity.eset.com,identity.gtm.eset.com,identity.kde.org,identity.lego.com,identity.walmart.com,idmsa.apple.com,idmsa.apple.com.cn,idmsac.apple.com,idp.ddp.akoya.com,idp.iam.mozilla.com,iforgot.apple.com,ing.com,ing.com.au,ingwb.com,iparitet.by,itsme-id.com,js.stripe.com,kairoscope.org,kbc.be,kdrp.okta.com,keytradebank.be,klarna.com,kraken.com,laptop-updates.brave.com,lastpass.com,lineageos.org,login.aa.com,login.advancedmd.com,login.amd.com,login.aol.com,login.corp.google.com,login.disney.com,login.eset.com,login.gov,login.kroger.com,login.live.com,login.mailbox.org,login.microsoftonline.com,login.nvgs.nvidia.com,login.okta.com,login.sparkasse.at,login.tailscale.com,login.wikimedia.org,login.yahoo.com,login.yahoo.net,login.xfinity.com,login-app.advancedmd.com,login-dev.advancedmd.com,login-no1a.www.tiktok.com,login3.id.hp.com,login4.fisglobal.com,lowes.syf.com,m.stripe.com,m.stripe.network,mail.proton.me,mailbox.org,marmon.okta.com,matrix.to,mblogin.verizonwireless.com,mebank.com.au,merchant-ui-api.stripe.com,microg.org,mirrorbits.lineageos.org,linuxmint.com,login.pnc.com,molly.im,monero.com,mpay24.com,msauth.net,msauthimages.net,msdl.gravesoft.dev,msftauth.net,msftauthimages.net,msp.nordpass.com,mt-bank.net,mtb.com,mullvad.net,my.collegeboard.org,my.dish.com,my.disney.com,my.eir.ie,myaccount.google.com,myaccount.microsoft.com,myaccounts.wizards.com,mychart.albanymed.org,mychart.asante.org,mychart.atlantichealth.org,mychart.austinregionalclinic.com,mychart.azacp.com,mychart.bmc.org,mychart.carolinaeasthealth.com,mychart.ccf.org,mychart.centracare.com,mychart.childrenscolorado.org,mychart.clevelandclinic.org,mychart.crmcwy.org,mychart.duly.com,mychart.ecommunity.com,mychart.hopkinsmedicine.org,mychart.inova.org,mychart.kansashealthsystem.com,mychart.lovelace.com,mychart.mainehealth.org,mychart.med.utah.edu,mychart.metrohealth.net,mychart.multicare.org,mychart.mwhc.com,mychart.nghs.com,mychart.nortonhealthcare.org,mychart.ohiohealth.com,mychart.orlandohealth.com,mychart.premierhealthpartners.org,mychart.selfregional.org,mychart.sfdph.org,mychart.sih.net,mychart.stcharleshealthcare.org,mychart.texashealth.org,mychart.tmcaz.com,mychart.uchospitals.edu,mychart.uconn.edu,mychart.uihealthcare.org,mychart.uillinois.edu,mychart.upstate.edu,mychart.urmc.rochester.edu,mychartonline.umassmemorial.org,myhealthchart.com,mysignins.microsoft.com,mysinaichicago.org,mystate.com.au,nab.com.au,nmi.com,nordaccount.com,nordpass.com,nordstrom.okta.com,noscript.net,novantmychart.org,nrc.okta.com,oauth.xfinity.com,oidc.idp.clogin.att.com,ok1static.oktacdn.com,ok2static.oktacdn.com,ok7static.oktacdn.com,okta.jumbo.com,oldsecond.com,onedrive.com,onedrive.live.com,online.citi.com,open-banking.pnc.com,openuserjs.org,outlook.com,outlook.office365.com,ow2-cqm-01.advancedmd.com,panel.nordpass.com,paritetbank.by,pass.proton.me,passwordreset.microsoftonline.com,passwords.google,passwords.google.com,patientportal.advancedmd.com,pay.amazon.co.jp,pay.amazon.co.uk,pay.amazon.com,pay.amazon.de,pay.amazon.es,pay.amazon.eu,pay.amazon.fr,pay.amazon.it,pay.google.com,pay.viasat.com,paybox.com,paybox.com.co,payconiq.be,payeezystrg.z19.web.core.windows.net,payments.amazon.com,payments-amazon.com,payoneer.com,payscout.com,paysend.com,payu.com,paywire.com,play.google.com,plex.direct,portal.corp.google.com,poste.dz,pp-wfe-100.advancedmd.com,ppixiv.org,privacybadger.org,probo.ddp.akoya.com,prod.idp.collegeboard.org,productdelivery.mozilla-backup.org,production.plaid.com,profile.theguardian.com,proton.me,protonapps.com,psendbank.com,qdoba-prod.us.auth0.com,raiffeisen.at,rb.okta.com,register.gitlab.gnome.org,register.mailbox.org,registerdisney.go.com,release.calyxinstitute.org,releases.mozilla.org,renault-bank-direkt.de,renaultbank.es,renaultbank.fr,retoswap.com,revolut.com,rh.okta.com,rpmfusion.org,secure.chase.com,secure.informaction.com,secure.login.gov,secure.myvirtua.org,secure.pnc.com,secure.sndcdn.com,secure.soundcloud.com,secure.verizon.com,secure-api.pnc.com,secure-qa.pnc.com,securelogin.synchronybank.com,secureonline.pnc.com,secureonline.yourstatebank.com,send.vis.ee,signal.org,signin.att.com,signin.aws.amazon.com,signin.costco.com,signin.ebay.com,signin-static-js.att.com,signup.ebay.com,skydrive.com,smartpay.profitstars.com,sso.canvaslms.com,sso.fachschaften.org,sso.kroger.com,sso.mozilla.com,sso.redhat.com,start.1password.ca,start.1password.com,start.1password.eu,static.adguard.com,static.adtidy.org,stgeorge.com.au,store.epicgames.com,store.nintendo.com.hk,studio.youtube.com,tam.onecampus.com,tpeweb.paybox.com,tuta.com,u.bank,ubank.bank,ubank.com.au,ubuntu.com,unbelgin.com,unionpayintl.com,unzer.com,up.com.au,us.download.nvidia.com,usaepay.com,usbank.com,vault.bitwarden.com,vault.bitwarden.eu,venmo.com,verifone.com,viewmychart.com,vpn.proton.me,wallet.google,wallet.google.com,wallet.proton.me,wero-wallet.eu,westpac.co.nz,westpac.com.au,wiki.lineageos.org,wise.com,www.365online.com,www.chase.com,www.citi.com,www.citidirect.com,www.cromite.org,www.dashlane.com,www.debian.org,www.easybank.at,www.easybanking.net,www.eff.org,www.epicgames.com,www.firefox.com,www.franciscanmychart.org,www.gigabyte.com,www.icloud.com,www.icloud.com.cn,www.intel.com,www.lineageos.org,www.linuxmint.com,www.macquarie.com.au,www.mozilla.org,www.mychart.org,www.noscript.net,www.onlinebanking.pnc.com,www.paypal.com,www.paypalobjects.com,www.pnc.com,www.privacy.com,www.privatebank.citibank.com,www.sparkasse.at,www.synchrony.com,www.synchronymastercard.com,www.thunderbird.net,www.torproject.org,www.virustotal.com,www.wintrustbank.com,www.wintrustdigitalbanking.com,www.xmrbazaar.com,www.yourstatebank.com,xmrbazaar.com";

    "extensions.userScripts.mv3.enabled" = true;
    "extensions.webextensions.userScripts.enabled" = true;
    "extensions.userContextIsolation.@testpilot-container.restricted" = "[]";
    "extensions.userContextIsolation.uBlock0@raymondhill.net.restricted" = "[]";
    "extensions.webcompat.useScriptingAPI" = true;
    "extensions.webextensions.base-content-security-policy" =
      "script-src 'self' 'unsafe-inline'; upgrade-insecure-requests;";
    "extensions.webextensions.base-content-security-policy.v3" =
      "script-src 'self'; upgrade-insecure-requests;";
    "extensions.webextensions.default-content-security-policy" =
      "script-src 'self'; upgrade-insecure-requests;";
    "extensions.webextensions.default-content-security-policy.v3" =
      "script-src 'self'; upgrade-insecure-requests;";
    "extensions.postDownloadThirdPartyPrompt" = false;
    "xpinstall.whitelist.directRequest" = false;
    "xpinstall.whitelist.fileRequest" = false;
    "xpinstall.whitelist.required" = true;
    "extensions.install.requireBuiltInCerts" = true;
    "extensions.update.requireBuiltInCerts" = true;
    "extensions.langpacks.signatures.required" = true;
    "xpinstall.signatures.required" = true;
    "extensions.originControls.grantByDefault" = false;
    "extensions.manifestV2.actionsPopupURLRestricted" = true;
    "extensions.openPopupWithoutUserGesture.enabled" = false;
    "extensions.geckoProfiler.acceptedExtensionIds" = "";
    "extensions.experiments.enabled" = false;
    "devtools.aboutdebugging.showHiddenAddons" = true;
    "extensions.content_web_accessible.enabled" = true;
    "extensions.install.requireSecureOrigin" = true;
    "xpinstall.blacklist.add.GNU" = "gnuzilla.gnu.org";

    "extensions.quarantineIgnoredByUser.{00000f2a-7cde-4f20-83ed-434fcb420d71}" = false; # / Imagus
    "extensions.quarantineIgnoredByUser.{1018e4d6-728f-4b20-ad56-37578a4de76b}" = false; # / Flagfox
    "extensions.quarantineIgnoredByUser.{154cddeb-4c8b-4627-a478-c7e5b427ffdf}" = false; # / PopUpOFF - Popup and overlay blocker
    "extensions.quarantineIgnoredByUser.{2e5ff8c8-32fe-46d0-9fc8-6b8986621f3c}" = false; # / Search by Image
    "extensions.quarantineIgnoredByUser.{32af1358-428a-446d-873e-5f8eb5f2a72e}" = false; # / Download All Images
    "extensions.quarantineIgnoredByUser.{3c078156-979c-498b-8990-85f7987dd929}" = false; # / Sidebery
    "extensions.quarantineIgnoredByUser.{4a313247-8330-4a81-948e-b79936516f78}" = false; # / Image Search Options
    "extensions.quarantineIgnoredByUser.{506e023c-7f2b-40a3-8066-bc5deb40aebe}" = false; # / Gesturefy
    "extensions.quarantineIgnoredByUser.{52bda3fd-dc48-4b3d-a7b9-58af57879f1e}" = false; # / Stylebot
    "extensions.quarantineIgnoredByUser.{531906d3-e22f-4a6c-a102-8057b88a1a63}" = false; # / SingleFile
    "extensions.quarantineIgnoredByUser.{5384767E-00D9-40E9-B72F-9CC39D655D6F}" = false; # / EPUBReader
    "extensions.quarantineIgnoredByUser.{54e2eb33-18eb-46ad-a4e4-1329c29f6e17}" = false; # / Block Site
    "extensions.quarantineIgnoredByUser.{63d150c4-394c-4275-bc32-c464e76a891c}" = false; # / Audio Equalizer
    "extensions.quarantineIgnoredByUser.{79b2e4de-8fb4-4ccc-b9f6-362ac2fb74b2}" = false; # / Measure-it
    "extensions.quarantineIgnoredByUser.{7a7a4a92-a2a0-41d1-9fd7-1e92480d612d}" = false; # / Stylus
    "extensions.quarantineIgnoredByUser.{7b1bf0b6-a1b9-42b0-b75d-252036438bdc}" = false; # / YouTube High Definition
    "extensions.quarantineIgnoredByUser.{91aa5abe-9de4-4347-b7b5-322c38dd9271}" = false; # / Clippings
    "extensions.quarantineIgnoredByUser.{a6c4a591-f1b2-4f03-b3ff-767e5bedf4e7}" = false; # / User-Agent Switcher and Manager
    "extensions.quarantineIgnoredByUser.{a9c2ad37-e940-4892-8dce-cd73c6cbbc0c}" = false; # / Feedbro
    "extensions.quarantineIgnoredByUser.{b9acf540-acba-11e1-8ccb-001fd0e08bd4}" = false; # / Easy Youtube Video Downloader Express
    "extensions.quarantineIgnoredByUser.{b9db16a4-6edc-47ec-a1f4-b86292ed211d}" = false; # / Video DownloadHelper
    "extensions.quarantineIgnoredByUser.{c2c003ee-bd69-42a2-b0e9-6f34222cb046}" = false; # / Auto Tab Discard
    "extensions.quarantineIgnoredByUser.{c5867acc-54c9-4074-9574-04d8818d53e8}" = false; # / Livemarks
    "extensions.quarantineIgnoredByUser.{d07ccf11-c0cd-4938-a265-2a4d6ad01189}" = false; # / Web Archives
    "extensions.quarantineIgnoredByUser.{d37dc5d0-431d-44e5-8c91-49419370caa1}" = false; # / FoxClocks
    "extensions.quarantineIgnoredByUser.{DDC359D1-844A-42a7-9AA1-88A850A938A8}" = false; # / DownThemAll!
    "extensions.quarantineIgnoredByUser.{de22fd49-c9ab-4359-b722-b3febdc3a0b0}" = false; # / Popup Blocker (strict
    "extensions.quarantineIgnoredByUser.{e839c3f9-298e-4cd0-99e0-464431cb7c34}" = false; # / Foxy Gestures
    "extensions.quarantineIgnoredByUser.{e90f5de4-8510-4515-9f67-3b6654e1e8c2}" = false; # / Dictionary Anywhere
    "extensions.quarantineIgnoredByUser.addon@darkreader.org" = false; # / Dark Reader
    "extensions.quarantineIgnoredByUser.adb@mozilla.org" = false; # / Firefox DevTools ADB Extension
    "extensions.quarantineIgnoredByUser.ads@mozac.org" = false; # / Mozilla Android Components - Ads Telemetry
    "extensions.quarantineIgnoredByUser.ATBC@EasonWong" = false; # / Adaptive Tab Bar Color
    "extensions.quarantineIgnoredByUser.cookies@mozac.org" = false; # / Mozilla Android Components - Search Telemetry
    "extensions.quarantineIgnoredByUser.copyplaintext@eros.man" = false; # / Copy PlainText
    "extensions.quarantineIgnoredByUser.customscrollbars@computerwhiz" = false; # / Custom Scrollbars
    "extensions.quarantineIgnoredByUser.dont-track-me-google@robwu.nl" = false; # / Don't track me Google
    "extensions.quarantineIgnoredByUser.ddg@search.mozilla.org" = false; # / DuckDuckGo - search engine
    "extensions.quarantineIgnoredByUser.deArrow@ajay.app" = false; # / DeArrow
    "extensions.quarantineIgnoredByUser.emoji@saveriomorelli.com" = false; # / Emoji
    "extensions.quarantineIgnoredByUser.firefox@ghostery.com" = false; # / Ghostery
    "extensions.quarantineIgnoredByUser.foxytab@eros.man" = false; # / Ghostery
    "extensions.quarantineIgnoredByUser.jid0-dsq67mf5kjjhiiju2dfb6kk8dfw@jetpack" = false; # / FoxyTab
    "extensions.quarantineIgnoredByUser.jid1-KdTtiCj6wxVAFA@jetpack" = false; # / Swift Selection Search
    "extensions.quarantineIgnoredByUser.jid1-q4sG8pYhq8KGHs@jetpack" = false; # / AdBlocker for YouTube™
    "extensions.quarantineIgnoredByUser.jid1-QoFqdK4qzUfGWQ@jetpack" = false; # / Dark Background and Light Text
    "extensions.quarantineIgnoredByUser.juraj.masiar@gmail.com_ScrollAnywhere" = false; # / ScrollAnywhere
    "extensions.quarantineIgnoredByUser.languagetool-webextension@languagetool.org" = false; # / LanguageTool
    "extensions.quarantineIgnoredByUser.leechblockng@proginosko.com" = false; # / LeechBlock NG
    "extensions.quarantineIgnoredByUser.linkgopher@oooninja.com" = false; # / Link Gopher
    "extensions.quarantineIgnoredByUser.printedit-we@DW-dev" = false; # / Print Edit WE
    "extensions.quarantineIgnoredByUser.s3download@statusbar" = false; # / Download Manager (S3
    "extensions.quarantineIgnoredByUser.simple-tab-groups@drive4ik" = false; # / Simple Tab Groups
    "extensions.quarantineIgnoredByUser.snaplinks@snaplinks.mozdev.org" = false; # / Snap Links
    "extensions.quarantineIgnoredByUser.soundfixer@unrelenting.technology" = false; # / SoundFixer
    "extensions.quarantineIgnoredByUser.sponsorBlocker@ajay.app" = false; # / SponsorBlock
    "extensions.quarantineIgnoredByUser.stefanvandamme@stefanvd.net" = false; # / Turn Off the Lights
    "extensions.quarantineIgnoredByUser.tabby@whatsyouridea.com" = false; # / Tabby - Window and Tab Manager
    "extensions.quarantineIgnoredByUser.tranquility@ushnisha.com" = false; # / Tranquility Reader
    "extensions.quarantineIgnoredByUser.treestyletab@piro.sakura.ne.jp" = false; # / Tree Style Tabs
    "extensions.quarantineIgnoredByUser.wikipedia@search.mozilla.org" = false; # / Wikipedia (en - search engine
    "extensions.quarantineIgnoredByUser.worldwide@radio" = false; # / Worldwide Radio
    "extensions.quarantineIgnoredByUser.zoompage-we@DW-dev" = false; # / Zoom Page WE
  };
}
