{...}: {
  "browser.ai.control.default" = "blocked";
  "browser.ai.control.linkPreviewKeyPoints" = "blocked";
  "browser.ai.control.pdfjsAltText" = "blocked";
  "browser.ai.control.sidebarChatbot" = "blocked";
  "browser.ai.control.smartTabGroups" = "blocked";
  "browser.ai.control.smartWindow" = "blocked";
  "browser.preferences.aiControls" = false;

  "extensions.htmlaboutaddons.local_model_management" = true;
  "browser.ml.enable" = false;
  "browser.ml.chat.enabled" = false;
  "browser.ml.chat.menu" = false;
  "browser.ml.chat.page" = false;
  "browser.ml.chat.sidebar" = false;
  "extensions.formautofill.ml.experiment.enabled" = false;
  "browser.aiwindow.apiKey" = "";
  "browser.aiwindow.enabled" = false;
  "browser.aiwindow.endpoint" = "";
  "browser.aiwindow.insights" = false;
  "browser.aiwindow.memories" = false;
  "browser.aiwindow.model" = "";
  "browser.smartwindow.apiKey" = "";
  "browser.smartwindow.enabled" = false;
  "browser.smartwindow.endpoint" = "";
  "browser.smartwindow.memories" = false;
  "browser.smartwindow.model" = "";
  "browser.smartwindow.preferences.endpoint" = "";
  "browser.ml.linkPreview.collapsed" = true;
  "browser.ml.linkPreview.longPress" = false;
  "browser.ml.linkPreview.optin" = false;
  "browser.ml.linkPreview.supportedLocales" = "null";
  "browser.ml.pageAssist.enabled" = false;
  "browser.urlbar.perplexity.hasBeenInSearchMode" = true;
  "places.semanticHistory.featureGate" = false;
  "browser.ml.smartAssist.apiKey" = "";
  "browser.ml.smartAssist.enabled" = false;
  "browser.ml.smartAssist.endpoint" = "";
  "browser.ml.smartAssist.model" = "";
  "browser.ml.smartAssist.overrideNewTab" = false;
  "extensions.ml.enabled" = false;
  "browser.tabs.groups.smart.enabled" = false;
  "browser.tabs.groups.smart.optin" = false;
  "browser.tabs.groups.smart.userEnabled" = false;
  "browser.ml.chat.providers" = "";
  "browser.ml.chat.provider" = "https://duck.ai/";

  ## Link Preview
  "browser.ml.linkPreview.enabled" = true;
  "browser.ml.linkPreview.blockListEnabled" = false;
}
